name: DEV DEPLOYMENT

on:
  push:
    branches:
      - master

jobs:
  deploy-komnasham:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to GCP komnasham.solusigudang.co
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            sudo bash
            cd ${{APP_DIR}}
            git checkout master
            git pull
            echo "yes" | composer update
